# Generated by Django 2.1.4 on 2019-01-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='med_name',
        ),
    ]
