# Generated by Django 2.1.4 on 2019-01-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20190112_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drug_class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='other',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
