# Generated by Django 2.1.4 on 2019-01-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('available_dates', models.CharField(max_length=200)),
                ('works_from', models.IntegerField()),
                ('works_upto', models.IntegerField()),
                ('init_date', models.IntegerField(default=1)),
                ('curr_status', models.IntegerField(default=0)),
                ('max_booking', models.IntegerField(default=70)),
            ],
        ),
        migrations.CreateModel(
            name='Testdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='testchoice',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='divaDoc.Testdoc'),
        ),
    ]
