# Generated by Django 2.1.4 on 2019-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divaDoc', '0003_auto_20190119_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='rateapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
