# Generated by Django 2.1.4 on 2018-12-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('available_dates', models.CharField(max_length=200)),
                ('init_date', models.IntegerField(default=1)),
            ],
        ),
    ]
