# Generated by Django 2.1.4 on 2019-01-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_pulmonologist_radiologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ophthalmologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('available_dates', models.CharField(max_length=200)),
                ('works_from', models.IntegerField()),
                ('works_upto', models.IntegerField()),
                ('init_date', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orthopedic_Surgeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('available_dates', models.CharField(max_length=200)),
                ('works_from', models.IntegerField()),
                ('works_upto', models.IntegerField()),
                ('init_date', models.IntegerField(default=1)),
            ],
        ),
    ]
