# Generated by Django 2.1.4 on 2019-01-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_ophthalmologist_orthopedic_surgeon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gynecologist',
            new_name='Gynaecologist',
        ),
        migrations.RenameModel(
            old_name='Orthopedic_Surgeon',
            new_name='Orthopaedic_Surgeon',
        ),
    ]
