# Generated by Django 2.1.4 on 2019-01-02 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20190101_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='curr_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dentist',
            name='max_booking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
