# Generated by Django 2.1.4 on 2019-01-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_remove_dentist_max_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='curr_status',
        ),
    ]
