# Generated by Django 2.1.4 on 2019-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_remove_dentist_curr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='curr_status',
            field=models.IntegerField(default=0),
        ),
    ]
