# Generated by Django 2.1.4 on 2019-01-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_dentist_curr_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
