# Generated by Django 2.1.4 on 2019-01-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_dentist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychiatrist',
            name='works_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psychiatrist',
            name='works_upto',
            field=models.IntegerField(default=0),
        ),
    ]
