# Generated by Django 2.1.4 on 2019-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_auto_20190102_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='max_booking',
            field=models.CharField(default='', max_length=10),
        ),
    ]
