# Generated by Django 2.1.4 on 2019-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_dentist_max_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='max_booking',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
    ]
