# Generated by Django 2.1.4 on 2019-01-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_auto_20190102_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='curr_status',
            field=models.IntegerField(default=60),
        ),
    ]
