# Generated by Django 2.1.4 on 2019-01-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_auto_20190102_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
