# Generated by Django 2.1.4 on 2019-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_delete_dentist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('available_dates', models.CharField(max_length=200)),
                ('init_date', models.IntegerField(default=1)),
                ('curr_status', models.IntegerField(default=60)),
                ('max_booking', models.CharField(default='', editable=False, max_length=10)),
            ],
        ),
    ]
