# Generated by Django 2.1.4 on 2019-01-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0023_dentist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='curr_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='max_booking',
            field=models.IntegerField(default=60),
        ),
    ]
