# Generated by Django 2.1.4 on 2019-01-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('certficate', models.FileField(upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('validity', models.BooleanField(default=False)),
                ('book_user_model', models.IntegerField(default=0)),
                ('time_book1_model', models.TimeField(default=None)),
                ('rating', models.FloatField(default=0)),
                ('profile', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
