# Generated by Django 2.1.4 on 2019-01-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='book_user_model',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patientName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
