# Generated by Django 2.1.4 on 2019-01-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20190120_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time_book1_model',
            field=models.CharField(default='', max_length=10),
        ),
    ]
