# Generated by Django 2.1.4 on 2019-01-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_auto_20190120_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_dates',
            field=models.CharField(default='date', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='curr_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='loc', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='max_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='worls_upto',
            field=models.IntegerField(default=0),
        ),
    ]
