# Generated by Django 2.1.4 on 2019-01-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20190120_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='worls_upto',
            new_name='works_upto',
        ),
    ]
