# Generated by Django 2.1.4 on 2019-01-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_auto_20190120_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patientName',
            field=models.CharField(default='patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time_book1_model',
            field=models.CharField(default='time', max_length=10),
        ),
    ]
